#!/usr/bin/env bash
# Default values for all @claudux_* tmux options
# Sourced by helpers.sh — never executed directly

CLAUDUX_DEFAULT_REFRESH_INTERVAL=300
CLAUDUX_DEFAULT_BAR_LENGTH=10
CLAUDUX_DEFAULT_WARNING_THRESHOLD=50
CLAUDUX_DEFAULT_CRITICAL_THRESHOLD=80
CLAUDUX_DEFAULT_SHOW_WEEKLY="on"
CLAUDUX_DEFAULT_SHOW_MONTHLY="on"
CLAUDUX_DEFAULT_SHOW_MODEL="on"
CLAUDUX_DEFAULT_SHOW_RESET="on"
CLAUDUX_DEFAULT_SHOW_EMAIL="off"
