#!/usr/bin/env bash
# Default values for all @claudux_* tmux options
# Sourced by helpers.sh — never executed directly

CLAUDUX_DEFAULT_REFRESH_INTERVAL=300
CLAUDUX_DEFAULT_BAR_LENGTH=10
CLAUDUX_DEFAULT_WARNING_THRESHOLD=50
CLAUDUX_DEFAULT_CRITICAL_THRESHOLD=80
CLAUDUX_DEFAULT_SHOW_WEEKLY="on"
CLAUDUX_DEFAULT_SHOW_MONTHLY="on"
CLAUDUX_DEFAULT_SHOW_MODEL="on"
CLAUDUX_DEFAULT_SHOW_RESET="on"
CLAUDUX_DEFAULT_SHOW_EMAIL="off"
CLAUDUX_DEFAULT_SHOW_COST="on"
CLAUDUX_DEFAULT_SHOW_VELOCITY="on"
CLAUDUX_DEFAULT_SHOW_CONTEXT="on"
CLAUDUX_DEFAULT_SHOW_MODEL_INDICATOR="on"
CLAUDUX_DEFAULT_SHOW_BURN="on"
CLAUDUX_DEFAULT_SHOW_SESSIONS="on"
CLAUDUX_DEFAULT_SHOW_RATE_LIMITS="on"
CLAUDUX_DEFAULT_SHOW_PREDICTOR="on"
CLAUDUX_DEFAULT_SHOW_VITALS="on"
CLAUDUX_DEFAULT_LABEL_MODE="verbose"
